local GUI = require "gui.gooey_theme_md"

function init(self)
	GUI.acquire_input()

	GUI.checkbox("checkbox").set_checked(true)
	GUI.radio("radio2").set_selected(true)
	GUI.scrollbar("scrollbar").scroll_to(0, 0.75) --also can set the scroll

end

function on_input(self, action_id, action)
	local group = GUI.group("group1", function()
		GUI.button("button", action_id,action, function(button)
			if button.long_pressed then
				print("Button was long pressed")
			else
				print("Button was pressed")
			end
		end)

		GUI.checkbox("checkbox", action_id, action, function(checkbox)
			print("checkbox", checkbox.checked)
		end)

		GUI.radiogroup("MYGROUP", action_id, action, function(group_id, action_id, action)
			GUI.radio("radio1", group_id, action_id, action, function(radio)
				print("radio 1", radio.selected)
			end)
			GUI.radio("radio2", group_id, action_id, action, function(radio)
				print("radio 2", radio.selected)
			end)
			GUI.radio("radio3", group_id, action_id, action, function(radio)
				print("radio 3", radio.selected)
			end)
		end)

		GUI.scrollbar("scrollbar", action_id, action, function(scrollbar)
			print("scrolled", scrollbar.scroll.y)
		end)
		
	end)
	return group.consumed
end
