local MY_GUI = require "gui.gooey_theme_md"


function init(self)
	MY_GUI.acquire_input()

	--MY_GUI.checkbox("checkbox").set_checked(true)
	--MY_GUI.radio("radio2").set_selected(true)
	--MY_GUI.scrollbar("scrollbar").scroll_to(0, 0.75) --also can set the scroll
	--MY_GUI.scrollbar_updatebar("scrollbar", 0.75)

end

function on_input(self, action_id, action)
	local group = MY_GUI.group("group1", function()
		MY_GUI.button_simple("button", action_id, action, function(button)
			if button.long_pressed then
				print("Button was long pressed")
			else
				print("Button was pressed")
			end
		end)

		MY_GUI.checkbox_simple("checkbox", action_id, action, function(checkbox)
			print("checkbox", checkbox.checked)
		end)

		MY_GUI.radiogroup("MYGROUP", action_id, action, function(group_id, action_id, action)
			MY_GUI.radio("radio1", group_id, action_id, action, function(radio)
				print("radio 1", radio.selected)
			end)
			MY_GUI.radio("radio2", group_id, action_id, action, function(radio)
				print("radio 2", radio.selected)
			end)
			MY_GUI.radio("radio3", group_id, action_id, action, function(radio)
				print("radio 3", radio.selected)
			end)
		end)

		MY_GUI.scrollbar_vertical("scrollbar", action_id, action, function(scrollbar)
			if scrollbar.pressed then
				MY_GUI.scrollbar_vertical_updatebar("scrollbar", scrollbar.scroll.y)
			end
			print("scrolled", scrollbar.scroll.y)
		end)

	end)
	return group.consumed
end
